# This is a generated file. Not intended for manual editing.
services:
  jornadamilhas.api:
    build:
      context: "/home/tacio/Documentos/Dev/C#/JornadaMilhas-API-rec-main"
      dockerfile: "src/JornadaMilhas.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/JornadaMilhas.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "jornadamilhasapi:dev"
    ports: []
    volumes:
    - "/home/tacio/Documentos/Dev/C#/JornadaMilhas-API-rec-main/src/JornadaMilhas.API:/app:rw"
    - "/home/tacio/Documentos/Dev/C#/JornadaMilhas-API-rec-main:/src:rw"
    - "/home/tacio/.nuget/packages:/root/.nuget/packages"
    working_dir: "/app"
